let toDos = [];
let projects = [];
let lists = document.querySelectorAll("aside ul li");
let ul = document.querySelector("aside ul");
let section = document.querySelector("section");
let newLi = [];
let titleField = document.querySelector("section .title-field");
let descField = document.querySelector("section .desc-field");
let dateField = document.querySelector("section .date-field");
let priorityField = document.querySelector("section .priority");
let personalProjects = [];
export { toDos, projects, lists, ul, newLi, section, dateField, descField, titleField, priorityField, personalProjects};